In [2]:
pip install ucimlrepo

Note: you may need to restart the kernel to use updated packages.


In [1]:
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
zoo = fetch_ucirepo(id=111) 
  
# data (as pandas dataframes) 
X = zoo.data.features 
y = zoo.data.targets 
  
# metadata 
print(zoo.metadata) 
  
# variable information 
print(zoo.variables) 


{'uci_id': 111, 'name': 'Zoo', 'repository_url': 'https://archive.ics.uci.edu/dataset/111/zoo', 'data_url': 'https://archive.ics.uci.edu/static/public/111/data.csv', 'abstract': 'Artificial, 7 classes of animals', 'area': 'Biology', 'tasks': ['Classification'], 'characteristics': ['Multivariate'], 'num_instances': 101, 'num_features': 16, 'feature_types': ['Categorical', 'Integer'], 'demographics': [], 'target_col': ['type'], 'index_col': ['animal_name'], 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 1990, 'last_updated': 'Fri Sep 15 2023', 'dataset_doi': '10.24432/C5R59V', 'creators': ['Richard Forsyth'], 'intro_paper': None, 'additional_info': {'summary': 'A simple database containing 17 Boolean-valued attributes.  The "type" attribute appears to be the class attribute.  Here is a breakdown of which animals are in which type: (I find it unusual that there are 2 instances of "frog" and one of "girl"!)', 'purpose': None, 'funded_by': None, 'inst

In [47]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix

df=pd.read_csv('C:/Users/User/Downloads/zoo.csv', header=0)
#drop Columnn 0 which contains the class names which we want our model to predict on. 
X=np.array(df.iloc[:, 1:17])
y=np.array(df['type'])
#split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.30,random_state=42)
knn= KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)
pred= knn.predict(X_test)
print('Index\tPredicted\tActual')
for i in range(len(pred)):
    if pred[i] != y_test[i]:
        print(i, '\t', pred[i], '\t\t', y_test[i], ' ****')
print('Accuracy Score:',accuracy_score(y_test,pred))
print('Confusion Matrix:')

print(confusion_matrix(y_test,pred))


Index	Predicted	Actual
20 	 4 		 3  ****
27 	 6 		 7  ****
Accuracy Score: 0.9354838709677419
Confusion Matrix:
[[15  0  0  0  0  0  0]
 [ 0  3  0  0  0  0  0]
 [ 0  0  0  1  0  0  0]
 [ 0  0  0  2  0  0  0]
 [ 0  0  0  0  2  0  0]
 [ 0  0  0  0  0  5  0]
 [ 0  0  0  0  0  1  2]]


animal_name  hair  feathers  eggs  milk  airborne  aquatic  predator  \
0    aardvark     1         0     0     1         0        0         1   
1    antelope     1         0     0     1         0        0         0   
2        bass     0         0     1     0         0        1         1   
3        bear     1         0     0     1         0        0         1   
4        boar     1         0     0     1         0        0         1   

   toothed  backbone  breathes  venomous  fins  legs  tail  domestic  catsize  \
0        1         1         1         0     0     4     0         0        1   
1        1         1         1         0     0     4     1         0        1   
2        1         1         0         0     1     0     1         0        0   
3        1         1         1         0     0     4     0         0        1   
4        1         1         1         0     0     4     1         0        1   

   type  
0     1  
1     1  
2     4  
3     1  
4     1

In [45]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

# Load the dataset
df = pd.read_csv('C:/Users/User/Downloads/zoo.csv',header=0)

# Assuming the first column 'animal_name' should not be used in the feature set
X = df.drop(columns=['animal_name', 'type'])  # Dropping non-feature and target column
y = df['type']  # Target variable which is 'type'

# Split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)

# Initialize and fit the K-Neighbors Classifier
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)

# Predict on the test set
pred = knn.predict(X_test)

# Ensure pred and y_test are numpy arrays (especially if they've been modified or are not as expected)
pred = np.array(pred)
y_test = np.array(y_test)

# Output results and error analysis
print('Index\tPredicted\tActual')
for i in range(len(pred)):
    if pred[i] != y_test[i]:
        print(f"{i}\t{pred[i]}\t\t{y_test[i]} ****")

# Calculate and print accuracy and confusion matrix
accuracy = accuracy_score(y_test, pred)
conf_matrix = confusion_matrix(y_test, pred)
print(f'Accuracy Score: {accuracy}')
print('Confusion Matrix:')
print(conf_matrix)


Index	Predicted	Actual
20	4		3 ****
27	6		7 ****
Accuracy Score: 0.9354838709677419
Confusion Matrix:
[[15  0  0  0  0  0  0]
 [ 0  3  0  0  0  0  0]
 [ 0  0  0  1  0  0  0]
 [ 0  0  0  2  0  0  0]
 [ 0  0  0  0  2  0  0]
 [ 0  0  0  0  0  5  0]
 [ 0  0  0  0  0  1  2]]
